# 개발자를 위한 실전 선형대수학

In [39]:
import numpy as np
import matplotlib.pyplot as plt
import math

## Chapter 1. 벡터, 파트1

### 벡터 덧셈

In [40]:
v = np.array([[1, 2]])
w = np.array([[4, -6]])
v + w

array([[ 5, -4]])

### 벡터 노름 계산

$||\mathbf v|| = \sqrt{\sum_{i=1}^n v_i^2}$

In [41]:
def norm(v):
  return np.sqrt(np.sum(v ** 2))

v = np.array([[3, 5, 1]])

print("res: {}, ans: {}".format(norm(v), np.linalg.norm(v)))

res: 5.916079783099616, ans: 5.916079783099616


### 단위 벡터

$\hat{\mathbf v} = {1 \over ||\mathbf v||} \mathbf v$

In [42]:
def identity(v):
  return v / norm(v)

v = identity(np.array([[3, 5, 1]]))
print("v: {}, norm: {}".format(v, norm(v)))

v: [[0.50709255 0.84515425 0.16903085]], norm: 1.0


### 임의 크기 벡터

In [43]:
def identity(v, s):
  return s * v / norm(v)

v = identity(np.array([[3, 5, 1]]), 3)
print("v: {}, norm: {}".format(v, norm(v)))

v: [[1.52127766 2.53546276 0.50709255]], norm: 3.0000000000000004


### 전치

In [44]:
def transpose(v):
  ret = np.zeros((v.shape[1], v.shape[0]))
  for i in range(v.shape[1]):
    ret[i][0] = v[0][i]
  return ret

v = np.array([[3, 5, 1]])

print("res:\n{}\n\nans:\n{}".format(transpose(v), v.T));

res:
[[3.]
 [5.]
 [1.]]

ans:
[[3]
 [5]
 [1]]


### 내적을 이용한 노름 계산

$\delta = \sum_{i=1}^n a_i b_i$

In [45]:
v = np.array([[3, 5, 1]])

print("res: {}, ans: {}".format(
    np.sqrt(np.dot(v, v.T)), np.linalg.norm(v)))

res: [[5.91607978]], ans: 5.916079783099616


### 내적의 교환 법칙

$\mathbf v^T \mathbf w = \mathbf w^T \mathbf v$

In [46]:
v = np.array([[3, 5, 1]])
w = np.array([[4, 3, 7]])

print("v * w: {}, w * v: {}".format(np.sum(v * w), np.sum(w * v)))

v * w: 34, w * v: 34


## Chapter 2. 벡터, 파트 2

### 선형가중결합

$\mathbf{w} = \lambda_1 \mathbf{v}_1 + \lambda_2 \mathbf{v}_2 + \cdots + \lambda_n \mathbf{v}_n$

In [47]:
v = np.array([[4, 5, 1], [-4, 0, -4], [1, 3, 2]])
l = [1, 2, -3]
w = np.zeros((3, 1))

for i in range(3):
  for j in range(3):
    w[i] += l[j] * v[j][i]

print("w = l * v =\n{}".format(w))

w = l * v =
[[ -7.]
 [ -4.]
 [-13.]]


## Chapter 3. 벡터 응용

### 피어슨 상관계수와 코사인 유사도

In [64]:
def normalize(x):
  ret = np.zeros(len(x))
  mean = np.sum(x) / len(x)
  for i in range(len(x)):
    ret[i] = x[i] - mean
  return ret

def corrcoef(x, y):
  xh = normalize(x)
  yh = normalize(y)
  return np.dot(xh.T, yh) / (np.linalg.norm(xh) * np.linalg.norm(yh))

def cosinesim(x, y):
  return np.dot(x.T, y) / (np.linalg.norm(x) * np.linalg.norm(y))

v = np.array([0, 1, 2, 3])
w = np.array([100, 101, 102, 103])

print("correlation coefficient: {}".format(corrcoef(v, w)))
print("cosine similarity: {}".format(cosinesim(v, w)))

correlation coefficient: 0.9999999999999998
cosine similarity: 0.8083174787557303


### 에지 검출기

In [108]:
kernel = np.array([-1, 1])

data = np.zeros(30)
data[:10] = -1
data[10:20] = 1
data[20:] = -1

for i in range(1, len(data) - 1):
  print("{}: {}".format(data[i], np.dot(data[i-1:i+1].T, kernel)))

-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
1.0: 2.0
1.0: 0.0
1.0: 0.0
1.0: 0.0
1.0: 0.0
1.0: 0.0
1.0: 0.0
1.0: 0.0
1.0: 0.0
1.0: 0.0
-1.0: -2.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
