# 개발자를 위한 실전 선형대수학

In [148]:
import numpy as np
import matplotlib.pyplot as plt
import math

## Chapter 1. 벡터, 파트1

### 벡터 덧셈

In [149]:
v = np.array([[1, 2]])
w = np.array([[4, -6]])
v + w

array([[ 5, -4]])

### 벡터 노름 계산

$||\mathbf v|| = \sqrt{\sum_{i=1}^n v_i^2}$

In [150]:
def norm(v):
  return np.sqrt(np.sum(v ** 2))

v = np.array([[3, 5, 1]])

print("res: {}, ans: {}".format(norm(v), np.linalg.norm(v)))

res: 5.916079783099616, ans: 5.916079783099616


### 단위 벡터

$\hat{\mathbf v} = {1 \over ||\mathbf v||} \mathbf v$

In [151]:
def identity(v):
  return v / norm(v)

v = identity(np.array([[3, 5, 1]]))
print("v: {}, norm: {}".format(v, norm(v)))

v: [[0.50709255 0.84515425 0.16903085]], norm: 1.0


### 임의 크기 벡터

In [152]:
def identity(v, s):
  return s * v / norm(v)

v = identity(np.array([[3, 5, 1]]), 3)
print("v: {}, norm: {}".format(v, norm(v)))

v: [[1.52127766 2.53546276 0.50709255]], norm: 3.0000000000000004


### 전치

In [153]:
def transpose(v):
  ret = np.zeros((v.shape[1], v.shape[0]))
  for i in range(v.shape[1]):
    ret[i][0] = v[0][i]
  return ret

v = np.array([[3, 5, 1]])

print("res:\n{}\n\nans:\n{}".format(transpose(v), v.T));

res:
[[3.]
 [5.]
 [1.]]

ans:
[[3]
 [5]
 [1]]


### 내적을 이용한 노름 계산

$\delta = \sum_{i=1}^n a_i b_i$

In [154]:
v = np.array([[3, 5, 1]])

print("res: {}, ans: {}".format(
    np.sqrt(np.dot(v, v.T)), np.linalg.norm(v)))

res: [[5.91607978]], ans: 5.916079783099616


### 내적의 교환 법칙

$\mathbf v^T \mathbf w = \mathbf w^T \mathbf v$

In [155]:
v = np.array([[3, 5, 1]])
w = np.array([[4, 3, 7]])

print("v * w: {}, w * v: {}".format(np.sum(v * w), np.sum(w * v)))

v * w: 34, w * v: 34


## Chapter 2. 벡터, 파트 2

### 선형가중결합

$\mathbf{w} = \lambda_1 \mathbf{v}_1 + \lambda_2 \mathbf{v}_2 + \cdots + \lambda_n \mathbf{v}_n$

In [156]:
v = np.array([[4, 5, 1], [-4, 0, -4], [1, 3, 2]])
l = [1, 2, -3]
w = np.zeros((3, 1))

for i in range(3):
  for j in range(3):
    w[i] += l[j] * v[j][i]

print("w = l * v =\n{}".format(w))

w = l * v =
[[ -7.]
 [ -4.]
 [-13.]]


## Chapter 3. 벡터 응용

### 피어슨 상관계수와 코사인 유사도

In [157]:
def normalize(x):
  ret = np.zeros(len(x))
  mean = np.sum(x) / len(x)
  for i in range(len(x)):
    ret[i] = x[i] - mean
  return ret

def corrcoef(x, y):
  xh = normalize(x)
  yh = normalize(y)
  return np.dot(xh.T, yh) / (np.linalg.norm(xh) * np.linalg.norm(yh))

def cosinesim(x, y):
  return np.dot(x.T, y) / (np.linalg.norm(x) * np.linalg.norm(y))

v = np.array([0, 1, 2, 3])
w = np.array([100, 101, 102, 103])

print("correlation coefficient: {}".format(corrcoef(v, w)))
print("cosine similarity: {}".format(cosinesim(v, w)))

correlation coefficient: 0.9999999999999998
cosine similarity: 0.8083174787557303


### 에지 검출기

In [158]:
kernel = np.array([-1, 1])

data = np.zeros(30)
data[:10] = -1
data[10:20] = 1
data[20:] = -1

for i in range(1, len(data) - 1):
  print("{}: {}".format(data[i], np.dot(data[i-1:i+1].T, kernel)))

-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
1.0: 2.0
1.0: 0.0
1.0: 0.0
1.0: 0.0
1.0: 0.0
1.0: 0.0
1.0: 0.0
1.0: 0.0
1.0: 0.0
1.0: 0.0
-1.0: -2.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0
-1.0: 0.0


## Chapter 4. 행렬, 파트 1

### 행렬 원소 추출

In [159]:
M = np.arange(12).reshape(3, 4)

r = 1
c = 3

print(M)
print("The matrix element at index ({}, {}) is {}".format(r+1, c+1, M[r][c]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The matrix element at index (2, 4) is 7


### 부분 행렬 추출

In [160]:
C = np.arange(100).reshape(10, 10)
print(C)

C1 = C[5::1,:5:1]
C2 = C[5::1,5::1]
C3 = C[:5:1,5::1]
C4 = C[:5:1,:5:1]
print(np.array([C2, C1, C3, C4]).reshape(10, 10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[55 56 57 58 59 65 66 67 68 69]
 [75 76 77 78 79 85 86 87 88 89]
 [95 96 97 98 99 50 51 52 53 54]
 [60 61 62 63 64 70 71 72 73 74]
 [80 81 82 83 84 90 91 92 93 94]
 [ 5  6  7  8  9 15 16 17 18 19]
 [25 26 27 28 29 35 36 37 38 39]
 [45 46 47 48 49  0  1  2  3  4]
 [10 11 12 13 14 20 21 22 23 24]
 [30 31 32 33 34 40 41 42 43 44]]


### 행렬 덧셈

In [161]:
A = np.array([[2, 3, 4], [1, 2, 4]])
B = np.array([[0, 3, 1], [-1, -4, 2]])

C = np.zeros((2, 3))
for i in range(2):
  for j in range(3):
    C[i,j] = A[i,j] + B[i,j]

print(C)

[[ 2.  6.  5.]
 [ 0. -2.  6.]]


### 행렬 덧셈과 스칼라 곱셈의 교환/분배 법칙

$\sigma(A + B) = \sigma A + \sigma B = A \sigma + B \sigma$

In [162]:
A = np.random.randn(3, 4)
B = np.random.randn(3, 4)
s = np.random.randn()

C1 = s * (A + B)
C2 = s * A + s * B
C3 = A * s + B * s

print(C1)
print(C2)
print(C3)

print(np.isclose(C1, C2))
print(np.isclose(C2, C3))

[[-0.91963512  0.30574889  0.40090057 -0.00851239]
 [ 0.32665349 -0.75343797  0.77415184  0.08801907]
 [ 0.34436519 -1.22663214 -0.39339008  0.87263356]]
[[-0.91963512  0.30574889  0.40090057 -0.00851239]
 [ 0.32665349 -0.75343797  0.77415184  0.08801907]
 [ 0.34436519 -1.22663214 -0.39339008  0.87263356]]
[[-0.91963512  0.30574889  0.40090057 -0.00851239]
 [ 0.32665349 -0.75343797  0.77415184  0.08801907]
 [ 0.34436519 -1.22663214 -0.39339008  0.87263356]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


### 행렬 곱셈

In [163]:
A = np.random.randn(3, 5)
B = np.random.randn(5, 3)

C = np.zeros((3, 3))
for i in range(3):
  for j in range(3):
    C[i,j] = np.dot(A[i,:], B[:,j])

print(C)
print(A @ B)
print(np.isclose(C, A @ B))

[[-2.83153695 -3.05274489  4.22999434]
 [-0.79068696  0.73548158  0.76574581]
 [ 1.25043596 -1.662077   -1.38436088]]
[[-2.83153695 -3.05274489  4.22999434]
 [-0.79068696  0.73548158  0.76574581]
 [ 1.25043596 -1.662077   -1.38436088]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### LIVE EVIL 규칙

$(LIVE)^T = E^T V^T I^T L^T$

In [164]:
L = np.random.randn(2, 6)
I = np.random.randn(6, 3)
V = np.random.randn(3, 5)
E = np.random.randn(5, 2)

LIVE = (L @ I @ V @ E).T
EVIL = E.T @ V.T @ I.T @ L.T

print(LIVE)
print(EVIL)
print(np.isclose(LIVE, EVIL))

[[ 5.92947391 -5.11652811]
 [-3.52679336  2.35117864]]
[[ 5.92947391 -5.11652811]
 [-3.52679336  2.35117864]]
[[ True  True]
 [ True  True]]


### 대칭 행렬

In [165]:
def is_symmetric(a):
  diff = a.T - a
  for i in range(diff.shape[0]):
    for j in range(diff.shape[1]):
      if not np.isclose(diff[i,j], 0): return False
  return True

print(is_symmetric(np.array([[1, 0 ,0], [0, 1, 0], [0, 0, 1]])))
print(is_symmetric(np.array([[1, 1 ,0], [0, 1, 1], [1, 0, 1]])))
print(is_symmetric(np.array([[1, 0 ,1],
                             [0, 0, 1],
                             [1, 1, 1]])))

True
False
True
