# Chapter 1. 벡터, 파트1

In [92]:
import numpy as np
import matplotlib.pyplot as plt
import math

## 1-1. 벡터 덧셈

In [93]:
v = np.array([[1, 2]])
w = np.array([[4, -6]])
v + w

array([[ 5, -4]])

## 1-2. 벡터 노름 계산

$||\mathbf v|| = \sqrt{\sum_{i=1}^n v_i^2}$

In [111]:
def norm(v):
  return np.sqrt(np.sum(v ** 2))

v = np.array([[3, 5, 1]])

print("res: {}, ans: {}".format(norm(v), np.linalg.norm(v)))

res: 5.916079783099616, ans: 5.916079783099616


## 1-3. 단위 벡터

$\hat{\mathbf v} = {1 \over ||\mathbf v||} \mathbf v$

In [95]:
def identity(v):
  return v / norm(v)

v = identity(np.array([[3, 5, 1]]))
print("v: {}, norm: {}".format(v, norm(v)))

v: [[0.50709255 0.84515425 0.16903085]], norm: 1.0


## 1-4. 임의 크기 벡터

In [96]:
def identity(v, s):
  return s * v / norm(v)

v = identity(np.array([[3, 5, 1]]), 3)
print("v: {}, norm: {}".format(v, norm(v)))

v: [[1.52127766 2.53546276 0.50709255]], norm: 3.0000000000000004


## 1-5. 전치

In [116]:
def transpose(v):
  ret = np.zeros((v.shape[1], v.shape[0]))
  for i in range(v.shape[1]):
    ret[i][0] = v[0][i]
  return ret

v = np.array([[3, 5, 1]])

print("res:\n{} \n\n ans:\n{}".format(transpose(v), v.T));

res:
[[3.]
 [5.]
 [1.]] 

 ans:
[[3]
 [5]
 [1]]


## 1-6. 내적을 이용한 노름 계산

$\delta = \sum_{i=1}^n a_i b_i$

In [119]:
v = np.array([[3, 5, 1]])

print("res: {}, ans: {}".format(
    np.sqrt(np.dot(v, v.T)), np.linalg.norm(v)))

res: [[5.91607978]], ans: 5.916079783099616


## 1-7. 내적의 교환 법칙

$\mathbf v^T \mathbf w = \mathbf w^T \mathbf v$

In [142]:
v = np.array([[3, 5, 1]])
w = np.array([[4, 3, 7]])

print("v * w: {}, w * v: {}\n".format(np.sum(v * w), np.sum(w * v)))

v * w: 34, w * v: 34

